{% set name = "wxnatpy" %}
{% set version = "0.3.2" %}
{% set sha256 = "252c07d63caaca94beb3a73016a65eb6807d92387b6f396e061bf0408801ac82" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - wxpython >=4
    - xnat >=0.3.3
    - fsleyes-widgets >=0.3.1


test:
  commands:
    - python -c "import wxnat"


about:
  home: https://github.com/pauldmccarthy/wxnatpy
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A wxPython widget for browsing a XNAT repository'
  dev_url: https://github.com/pauldmccarthy/wxnatpy

extra:
  recipe-maintainers:
    - pauldmccarthy
