travis:
  secure:
    BINSTAR_TOKEN: ISWLNPVbSy3Y7y9OsgztmcyYmUy65OMRPZH6IP11P/407Ok4Hb7WcNBSFPb5h/V5n1KvqBoDD7tbA46dtXHK/XZI7BQoVgbIxh3ldhq7ZM4URpgxsR8mTUDkSwtUS985uE56qKW2AjXO1sX6ebYNx121YNfZ95i/RgVIaXod0vY57hmJx9eJLTYDSiGfOqWaaGmLucujjE2WjokAjW/s7E8ZSE/0vpDpNvQCd06sU+YusNuGdSdvTgkr1vRA+n5hG5y10SFq7fXkrqHzfepdCNxziXTNaqz2UgwbAAusbeLnyIl8YhE6ozWWJNG245CHoFeuvjnJYFKpWCPqhVPIujG2Ki4pwBwdzCEt61/vFCNwVhHAbmzOO2sh6vgANzJmbq437RPsC5I8NFbmDhMdi7RFbvWA8lxe1IXv9MHnwsMPiPcGlPHAqdN/7DDfgSBBRDrS902IijDP6UuqaWh8YwfvPSOyPG61yHGRZ19xhqrlpk/L7I0IbtIMpvyrnK5kiYj2DLb+HfPdAIQjoGebldcgtq682+Odh7una12aJLZ/JOfT5Bo5csmIKGad8qRNOcJtlIgwec8IgOZsKrapvCGu2UjVHZIYzwuOYwEMOJ0tm0gIKsEQW35nCY7O1r9oEL8PW2fNNoLHxkNNlTl4agX3Irm2LG/utV3Vw+1gW1A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
