travis:
  secure:
    BINSTAR_TOKEN: k97R0ZMpEIMbA5clbXtG4fVJtMLbu5UXLVILzrOJvpXepJ3XNbUkXpjvVTku/9ZeT55mP+Bzu8G+6T7e7Z3BWxDamdnZ5eb3Q3AZGEXW+WxrZUFSrdpLaS7LojNEBr3GGaPZXAQz7Jl31mLD/4kez1AhMNrF3J+6ycQXHD2E/tKLnLv+lGoeUAw0Yxh1EekXox0T6pGOhqTgse0zp/WXBcugy5PKNMDX5Z4dRKCgQU0gOPP+BWdXjxQc5H+jsZ09KZfAq6zuFZAT6r7sX1jrqGojazlegz8yY9vfs7aHrNnY2D275CpACVAyPVXPd7pgsWaGahEIHp54hSmqbsHV2qp4xMB+X5isWe2CAsiO3YXgUlPzvb5BX/UdX8LhQ4GZgWYXzzxGdDeHg+EG83QM+OuWlE0hKCg7xEFpgROGBiZ8YKs7Oy63b0pvvSfiI/YKx+/m+yt5lQgaZV80TokuwvZSvKXrX9EHM27t9g1gY6GzfMNw7q/2q9qYYIRPGhb1DVHqjbzl0czPW3HR7+PJO2IFYoW50RR5qdjHvr42GgXpjfgiKzpRyqa0PvCTG8AL4Ue32J1fhmfw6BeSWI7bK2GMbIeXSzUzhq7gkJm70EMSZ048YjfCGqjxccZV/HL2gcCD44h4n/gLsxUzTDOtQmbEEVY1zDvqx41DTgI6vy0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
